import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modalContainer: {
    backgroundColor: "#fff",
    alignItems: "center",
    marginHorizontal: 20,
    maxWidth: 330,
    borderRadius: 5,
    paddingVertical: 15,
  },
  actions_button: {
    backgroundColor: "#FDB72E",
    padding: 15,
    width: "100%",
    paddingHorizontal: 35,
    marginTop: 30,
  },
  actions_text: {
    fontSize: 16,
    fontFamily: "FredokaOne",
    textAlign: "center",
    color: "#fff",
  },
  title_form: {
    fontFamily: "FredokaOne",
    fontSize: 18,
    color: "#000",
    textAlign: "center",
    marginTop: 20,
    width: 330,
    paddingHorizontal: 20,
  },
  subtitle_form: {
    fontFamily: "FredokaOne",
    fontSize: 18,
    color: "#538CAE",
    textAlign: "center",
    marginTop: 20,
    paddingHorizontal: 20,
  },
  renderImageContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  renderContentContainer: {
    flex: 1,
    padding: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  renderContainer: {
    flex: 1,
    borderRadius: 8,
    padding: 5,
  },
  paginationContainerStyle: {
    paddingVertical: 5,
    marginBottom: 5,
    backgroundColor: "transparent",
    justifyContent: "center",
  },
  paginationDotContainerStyle: {
    marginHorizontal: 1,
  },
  paginationDotStyle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#80caa7",
  },
  form_input: {
    backgroundColor: "transparent",
    borderBottomColor: "#979797",
    borderBottomWidth: 1,
    color: "#323B45",
    // fontFamily: "RobotoRegular",
    fontSize: 15,
    flex: 0,
    height: 30,
    padding: 0,
    width: "100%",
  },
  form_input_container: {
    flexDirection: "column",
    gap: 5,
    alignItems: "center",
    width: 270,
    justifyContent: "center",
  },
  label_status: {
    color: "red",
    position: "absolute",
    right: 0,
  },
  label_input: {
    // fontFamily: "RobotoBold",
    fontSize: 16,
    fontWeight: "bold",
    color: "#5C6979",
    marginTop: 10,
    textAlign: "left",
    alignSelf: "flex-start",
    marginLeft: 5,
  },
});
